bills_ui/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

app_name = "bill_ui"

urlpatterns = (
    url(r'^$|^list$', views.bills, name='list'),
    url(r'^create', views.create, name='create'),
    url(r'^getBill$', views.find_bill_by_id, name='find_bill_by_id'),
    # url(r'^(?P<pk>[0-9]+)$', FindBillByID, name='find_bill_by_id'),
)

tags/urls.py
from django.conf.urls import include, url
from .views import tag_list, tag_detail, tag_list_by_name, tag_list_by_bill

urlpatterns = (
    url(r'^$', tag_list, name='tag_list'),
    url(r'^(?P<pk>[0-9]+)$', tag_detail, name='tag_list'),
    url(r'^(?P<tagname>\w+)/$', tag_list_by_name, name='tag_list_by_name'),
    url(r'^bills/(?P<bill>[0-9]+)/$', tag_list_by_bill, name='tag_list_by_bill'),
)

web_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

import views

urlpatterns = [
    url(r'^$|^index/', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^bills/', include('bills_ui.urls')),
    url(r'^api/bills/', include('bills.urls')),
    url(r'^api/tags/', include('tags.urls')),

]

web_app/views.py
from django.http import HttpResponse
from django.template import loader


def index(request):
    template = loader.get_template('index/index.html')
    context = {
        'content': 'Index',
    }
    return HttpResponse(template.render(context, request))

web_app/templates/index/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Spend Management - Bill</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/index.css' %}"/>
    <link href="{% static 'css/fontawesome-all.css' %}" rel="stylesheet"/>
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
</head>
<body>
{{bill.amount}}
<nav class="navbar navbar-inverse bg-green menu-bill">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand name-brand" href="#">Spend Management</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Bill
                    <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'bill_ui:create' %}">New Bill</a></li>
                    <li><a href="{% url 'bill_ui:list' %}">Bill List</a></li>
                </ul>
            </li>
            <li><a href="#">Report</a></li>
        </ul>
    </div>
</nav>
<div class="row">

</div>

<script src="{% static 'javascript/jquery.min.js' %}"></script>
<script src="{% static 'javascript/bootstrap.min.js' %}"></script>
<script src="{% static 'javascript/slideAnimation.js' %}"></script>
<script src="{% static 'javascript/fontawesome-all.js' %}"></script>
<script src="{% static 'javascript/index.js' %}"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( "#datepicker" ).datepicker({
        dateFormat: "yy-mm-dd"
    });
  } );
</script>
</body>
</html>